name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # dispara o deploy sempre que você fizer push na main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instala dependências e gera build
      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path docs --base-href /DEBORAH-LINDA/

      # 4️⃣ Commit do diretório docs/ com os arquivos do site
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs -f
          git commit -m "Deploy automático via GitHub Actions" || echo "Nada para commitar"
          git push
